from dj_rest_auth.registration.views import ResendEmailVerificationView
from .serializers import CustomResendEmailVerificationSerializer


class CustomResendEmailVerificationView(ResendEmailVerificationView):
    serializer_class = CustomResendEmailVerificationSerializer
